---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ketsiso2
spec:
  selector:
    matchLabels:
      app: ketsiso2
  replicas: 1
  template:
    metadata:
      labels:
        app: ketsiso2
    spec:
      containers:
        - name: ketsiso2
          image: passarinho/ketsiso
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: NODE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP

---
apiVersion: v1
kind: Service
metadata:
  name: ketsiso2
spec:
  selector:
    app: ketsiso2
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
