---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: testserver
spec:
  selector:
    matchLabels:
      app: testserver
  replicas: 6
  template:
    metadata:
      labels:
        app: testserver
    spec:
      containers:
        - name: testserver
          image: passarinho/testserver
          imagePullPolicy: Always
          ports:
            - containerPort: 8090
          env:
            - name: NODE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP


---
apiVersion: v1
kind: Service
metadata:
  name: testserver
spec:
  selector:
    app: testserver
  ports:
    - name: http
      port: 8090
      targetPort: 8090




